version: "2"

run:
  timeout: 5m
  tests: true

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - durationcheck
    - errorlint
    - misspell
    - noctx
    - prealloc
    - sqlclosecheck
    - unconvert
    - whitespace
  disable:
    - errcheck    # Too many false positives in defers
    - gosec       # Too many false positives for type conversions
    - predeclared # Conflicts with Go 1.21+ min/max builtins
    - exhaustive  # Too strict
    - nilerr      # False positives
    - unparam     # Too noisy
    - gocritic    # Style checks too strict

settings:
  govet:
    disable:
      - fieldalignment

  misspell:
    locale: US

exclusions:
  generated: lax
  presets:
    - comments
    - std-error-handling
  rules:
    - path: _test\.go
      linters:
        - staticcheck

    - path: internal/db/sqlc/
      linters:
        - govet
        - staticcheck

    - path: cmd/
      linters:
        - noctx

    - linters:
        - staticcheck
      text: SA1019

    - linters:
        - staticcheck
      text: ST1023
