// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type AnnotationQueue struct {
	ID         int32              `json:"id"`
	ItemID     pgtype.UUID        `json:"item_id"`
	Status     string             `json:"status"`
	AssignedTo pgtype.Int8        `json:"assigned_to"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
	Label      pgtype.Text        `json:"label"`
	Comment    pgtype.Text        `json:"comment"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Channel struct {
	ID                      pgtype.UUID        `json:"id"`
	TgPeerID                int64              `json:"tg_peer_id"`
	Username                pgtype.Text        `json:"username"`
	Title                   pgtype.Text        `json:"title"`
	IsActive                bool               `json:"is_active"`
	AddedAt                 pgtype.Timestamptz `json:"added_at"`
	AddedByTgUser           pgtype.Int8        `json:"added_by_tg_user"`
	AccessHash              pgtype.Int8        `json:"access_hash"`
	InviteLink              pgtype.Text        `json:"invite_link"`
	Context                 pgtype.Text        `json:"context"`
	Description             pgtype.Text        `json:"description"`
	LastTgMessageID         int64              `json:"last_tg_message_id"`
	Category                pgtype.Text        `json:"category"`
	Tone                    pgtype.Text        `json:"tone"`
	UpdateFreq              pgtype.Text        `json:"update_freq"`
	RelevanceThreshold      pgtype.Float4      `json:"relevance_threshold"`
	ImportanceThreshold     pgtype.Float4      `json:"importance_threshold"`
	ImportanceWeight        pgtype.Float4      `json:"importance_weight"`
	AutoWeightEnabled       pgtype.Bool        `json:"auto_weight_enabled"`
	WeightOverride          pgtype.Bool        `json:"weight_override"`
	WeightOverrideReason    pgtype.Text        `json:"weight_override_reason"`
	WeightUpdatedAt         pgtype.Timestamptz `json:"weight_updated_at"`
	WeightUpdatedBy         pgtype.Int8        `json:"weight_updated_by"`
	AutoRelevanceEnabled    pgtype.Bool        `json:"auto_relevance_enabled"`
	RelevanceThresholdDelta pgtype.Float4      `json:"relevance_threshold_delta"`
}

type ChannelQualityHistory struct {
	ID            pgtype.UUID        `json:"id"`
	ChannelID     pgtype.UUID        `json:"channel_id"`
	PeriodStart   pgtype.Date        `json:"period_start"`
	PeriodEnd     pgtype.Date        `json:"period_end"`
	InclusionRate float64            `json:"inclusion_rate"`
	NoiseRate     float64            `json:"noise_rate"`
	AvgImportance float64            `json:"avg_importance"`
	AvgRelevance  float64            `json:"avg_relevance"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ChannelRatingStat struct {
	ChannelID          pgtype.UUID        `json:"channel_id"`
	PeriodStart        pgtype.Date        `json:"period_start"`
	PeriodEnd          pgtype.Date        `json:"period_end"`
	WeightedGood       float64            `json:"weighted_good"`
	WeightedBad        float64            `json:"weighted_bad"`
	WeightedIrrelevant float64            `json:"weighted_irrelevant"`
	WeightedTotal      float64            `json:"weighted_total"`
	RatingCount        int32              `json:"rating_count"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ChannelStat struct {
	ID               int32              `json:"id"`
	ChannelID        pgtype.UUID        `json:"channel_id"`
	PeriodStart      pgtype.Date        `json:"period_start"`
	PeriodEnd        pgtype.Date        `json:"period_end"`
	MessagesReceived pgtype.Int4        `json:"messages_received"`
	ItemsCreated     pgtype.Int4        `json:"items_created"`
	ItemsDigested    pgtype.Int4        `json:"items_digested"`
	AvgImportance    pgtype.Float8      `json:"avg_importance"`
	AvgRelevance     pgtype.Float8      `json:"avg_relevance"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ChannelWeightHistory struct {
	ID                pgtype.UUID        `json:"id"`
	ChannelID         pgtype.UUID        `json:"channel_id"`
	ImportanceWeight  float32            `json:"importance_weight"`
	AutoWeightEnabled bool               `json:"auto_weight_enabled"`
	WeightOverride    bool               `json:"weight_override"`
	Reason            pgtype.Text        `json:"reason"`
	UpdatedBy         pgtype.Int8        `json:"updated_by"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Claim struct {
	ID              pgtype.UUID        `json:"id"`
	ClaimText       string             `json:"claim_text"`
	FirstSeenAt     pgtype.Timestamptz `json:"first_seen_at"`
	OriginClusterID pgtype.UUID        `json:"origin_cluster_id"`
	ClusterIds      []pgtype.UUID      `json:"cluster_ids"`
	ContradictedBy  []pgtype.UUID      `json:"contradicted_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Cluster struct {
	ID          pgtype.UUID        `json:"id"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
	WindowEnd   pgtype.Timestamptz `json:"window_end"`
	Topic       pgtype.Text        `json:"topic"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ClusterFirstAppearance struct {
	ClusterID   pgtype.UUID        `json:"cluster_id"`
	ChannelID   pgtype.UUID        `json:"channel_id"`
	FirstItemID pgtype.UUID        `json:"first_item_id"`
	FirstSeenAt pgtype.Timestamptz `json:"first_seen_at"`
}

type ClusterItem struct {
	ClusterID pgtype.UUID `json:"cluster_id"`
	ItemID    pgtype.UUID `json:"item_id"`
}

type ClusterLanguageLink struct {
	ClusterID       pgtype.UUID        `json:"cluster_id"`
	Language        string             `json:"language"`
	LinkedClusterID pgtype.UUID        `json:"linked_cluster_id"`
	Confidence      float32            `json:"confidence"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ClusterSummaryCache struct {
	DigestLanguage     string             `json:"digest_language"`
	ClusterFingerprint string             `json:"cluster_fingerprint"`
	ItemIds            []byte             `json:"item_ids"`
	Summary            string             `json:"summary"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ClusterTopicHistory struct {
	ID          pgtype.UUID        `json:"id"`
	ClusterID   pgtype.UUID        `json:"cluster_id"`
	Topic       string             `json:"topic"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
	WindowEnd   pgtype.Timestamptz `json:"window_end"`
}

type Digest struct {
	ID           pgtype.UUID        `json:"id"`
	WindowStart  pgtype.Timestamptz `json:"window_start"`
	WindowEnd    pgtype.Timestamptz `json:"window_end"`
	PostedChatID pgtype.Int8        `json:"posted_chat_id"`
	PostedMsgID  pgtype.Int8        `json:"posted_msg_id"`
	Status       string             `json:"status"`
	ErrorJson    []byte             `json:"error_json"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	PostedAt     pgtype.Timestamptz `json:"posted_at"`
}

type DigestEntry struct {
	ID          pgtype.UUID        `json:"id"`
	DigestID    pgtype.UUID        `json:"digest_id"`
	Title       pgtype.Text        `json:"title"`
	Body        string             `json:"body"`
	SourcesJson []byte             `json:"sources_json"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type DigestRating struct {
	ID        int32              `json:"id"`
	DigestID  pgtype.UUID        `json:"digest_id"`
	UserID    int64              `json:"user_id"`
	Rating    int16              `json:"rating"`
	Feedback  pgtype.Text        `json:"feedback"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DiscoveredChannel struct {
	ID                      pgtype.UUID        `json:"id"`
	Username                pgtype.Text        `json:"username"`
	TgPeerID                pgtype.Int8        `json:"tg_peer_id"`
	InviteLink              pgtype.Text        `json:"invite_link"`
	Title                   pgtype.Text        `json:"title"`
	SourceType              string             `json:"source_type"`
	DiscoveryCount          int32              `json:"discovery_count"`
	FirstSeenAt             pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt              pgtype.Timestamptz `json:"last_seen_at"`
	DiscoveredFromChannelID pgtype.UUID        `json:"discovered_from_channel_id"`
	Status                  string             `json:"status"`
	StatusChangedAt         pgtype.Timestamptz `json:"status_changed_at"`
	StatusChangedBy         pgtype.Int8        `json:"status_changed_by"`
	MaxViews                pgtype.Int4        `json:"max_views"`
	MaxForwards             pgtype.Int4        `json:"max_forwards"`
	EngagementScore         pgtype.Float4      `json:"engagement_score"`
	AccessHash              pgtype.Int8        `json:"access_hash"`
	ResolutionAttempts      pgtype.Int4        `json:"resolution_attempts"`
	LastResolutionAttempt   pgtype.Timestamptz `json:"last_resolution_attempt"`
	MatchedChannelID        pgtype.UUID        `json:"matched_channel_id"`
	Description             pgtype.Text        `json:"description"`
}

type Embedding struct {
	ItemID    pgtype.UUID        `json:"item_id"`
	Embedding pgvector.Vector    `json:"embedding"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type EnrichmentQueue struct {
	ID           pgtype.UUID        `json:"id"`
	ItemID       pgtype.UUID        `json:"item_id"`
	Summary      string             `json:"summary"`
	Status       string             `json:"status"`
	AttemptCount int32              `json:"attempt_count"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	NextRetryAt  pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type EnrichmentUsage struct {
	ID             pgtype.UUID        `json:"id"`
	Date           pgtype.Date        `json:"date"`
	Provider       string             `json:"provider"`
	RequestCount   int32              `json:"request_count"`
	EmbeddingCount int32              `json:"embedding_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CostUsd        pgtype.Numeric     `json:"cost_usd"`
}

type EvidenceClaim struct {
	ID           pgtype.UUID        `json:"id"`
	EvidenceID   pgtype.UUID        `json:"evidence_id"`
	ClaimText    string             `json:"claim_text"`
	EntitiesJson []byte             `json:"entities_json"`
	Embedding    pgvector.Vector    `json:"embedding"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type EvidenceSource struct {
	ID               pgtype.UUID        `json:"id"`
	Url              string             `json:"url"`
	UrlHash          string             `json:"url_hash"`
	Domain           string             `json:"domain"`
	Title            pgtype.Text        `json:"title"`
	Description      pgtype.Text        `json:"description"`
	Content          pgtype.Text        `json:"content"`
	Author           pgtype.Text        `json:"author"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	Language         pgtype.Text        `json:"language"`
	Provider         string             `json:"provider"`
	FetchedAt        pgtype.Timestamptz `json:"fetched_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	ExtractionFailed bool               `json:"extraction_failed"`
	SearchVector     interface{}        `json:"search_vector"`
}

type FactCheckCache struct {
	NormalizedClaim string             `json:"normalized_claim"`
	ResultJson      []byte             `json:"result_json"`
	CachedAt        pgtype.Timestamptz `json:"cached_at"`
}

type FactCheckQueue struct {
	ID              pgtype.UUID        `json:"id"`
	ItemID          pgtype.UUID        `json:"item_id"`
	Claim           string             `json:"claim"`
	NormalizedClaim string             `json:"normalized_claim"`
	Status          string             `json:"status"`
	AttemptCount    int32              `json:"attempt_count"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	NextRetryAt     pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Filter struct {
	ID        pgtype.UUID        `json:"id"`
	Type      string             `json:"type"`
	Pattern   string             `json:"pattern"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GlobalRatingStat struct {
	PeriodStart        pgtype.Date        `json:"period_start"`
	PeriodEnd          pgtype.Date        `json:"period_end"`
	WeightedGood       float64            `json:"weighted_good"`
	WeightedBad        float64            `json:"weighted_bad"`
	WeightedIrrelevant float64            `json:"weighted_irrelevant"`
	WeightedTotal      float64            `json:"weighted_total"`
	RatingCount        int32              `json:"rating_count"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Item struct {
	ID              pgtype.UUID        `json:"id"`
	RawMessageID    pgtype.UUID        `json:"raw_message_id"`
	RelevanceScore  float32            `json:"relevance_score"`
	ImportanceScore float32            `json:"importance_score"`
	Topic           pgtype.Text        `json:"topic"`
	Summary         pgtype.Text        `json:"summary"`
	Language        pgtype.Text        `json:"language"`
	Status          string             `json:"status"`
	ErrorJson       []byte             `json:"error_json"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	DigestedAt      pgtype.Timestamptz `json:"digested_at"`
	RetryCount      int32              `json:"retry_count"`
	NextRetryAt     pgtype.Timestamptz `json:"next_retry_at"`
	FactCheckScore  pgtype.Float4      `json:"fact_check_score"`
	FactCheckTier   pgtype.Text        `json:"fact_check_tier"`
	FactCheckNotes  pgtype.Text        `json:"fact_check_notes"`
	LanguageSource  pgtype.Text        `json:"language_source"`
	FirstSeenAt     pgtype.Timestamptz `json:"first_seen_at"`
	SearchVector    interface{}        `json:"search_vector"`
}

type ItemBullet struct {
	ID              pgtype.UUID        `json:"id"`
	ItemID          pgtype.UUID        `json:"item_id"`
	BulletIndex     int32              `json:"bullet_index"`
	Text            string             `json:"text"`
	Topic           pgtype.Text        `json:"topic"`
	RelevanceScore  pgtype.Float4      `json:"relevance_score"`
	ImportanceScore pgtype.Float4      `json:"importance_score"`
	Embedding       pgvector.Vector    `json:"embedding"`
	BulletHash      pgtype.Text        `json:"bullet_hash"`
	BulletClusterID pgtype.UUID        `json:"bullet_cluster_id"`
	Status          pgtype.Text        `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ItemEvidence struct {
	ID                pgtype.UUID        `json:"id"`
	ItemID            pgtype.UUID        `json:"item_id"`
	EvidenceID        pgtype.UUID        `json:"evidence_id"`
	AgreementScore    float32            `json:"agreement_score"`
	IsContradiction   bool               `json:"is_contradiction"`
	MatchedClaimsJson []byte             `json:"matched_claims_json"`
	MatchedAt         pgtype.Timestamptz `json:"matched_at"`
}

type ItemFactCheck struct {
	ID        pgtype.UUID        `json:"id"`
	ItemID    pgtype.UUID        `json:"item_id"`
	Claim     string             `json:"claim"`
	Url       string             `json:"url"`
	Publisher pgtype.Text        `json:"publisher"`
	Rating    pgtype.Text        `json:"rating"`
	MatchedAt pgtype.Timestamptz `json:"matched_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ItemRating struct {
	ID        int32              `json:"id"`
	ItemID    pgtype.UUID        `json:"item_id"`
	UserID    int64              `json:"user_id"`
	Rating    string             `json:"rating"`
	Feedback  pgtype.Text        `json:"feedback"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type LinkCache struct {
	ID              pgtype.UUID        `json:"id"`
	Url             string             `json:"url"`
	Domain          string             `json:"domain"`
	LinkType        string             `json:"link_type"`
	Title           pgtype.Text        `json:"title"`
	Content         pgtype.Text        `json:"content"`
	Author          pgtype.Text        `json:"author"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	Description     pgtype.Text        `json:"description"`
	ImageUrl        pgtype.Text        `json:"image_url"`
	WordCount       pgtype.Int4        `json:"word_count"`
	ChannelUsername pgtype.Text        `json:"channel_username"`
	ChannelTitle    pgtype.Text        `json:"channel_title"`
	ChannelID       pgtype.Int8        `json:"channel_id"`
	MessageID       pgtype.Int8        `json:"message_id"`
	Views           pgtype.Int4        `json:"views"`
	Forwards        pgtype.Int4        `json:"forwards"`
	HasMedia        pgtype.Bool        `json:"has_media"`
	MediaType       pgtype.Text        `json:"media_type"`
	Status          string             `json:"status"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	Language        pgtype.Text        `json:"language"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

type LlmUsage struct {
	ID               pgtype.UUID        `json:"id"`
	Date             pgtype.Date        `json:"date"`
	Provider         string             `json:"provider"`
	Model            string             `json:"model"`
	Task             string             `json:"task"`
	PromptTokens     int32              `json:"prompt_tokens"`
	CompletionTokens int32              `json:"completion_tokens"`
	RequestCount     int32              `json:"request_count"`
	CostUsd          pgtype.Numeric     `json:"cost_usd"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type MessageLink struct {
	RawMessageID pgtype.UUID `json:"raw_message_id"`
	LinkCacheID  pgtype.UUID `json:"link_cache_id"`
	Position     pgtype.Int4 `json:"position"`
}

type MvChannelOverlap struct {
	ChannelA       pgtype.UUID `json:"channel_a"`
	ChannelB       pgtype.UUID `json:"channel_b"`
	SharedClusters int64       `json:"shared_clusters"`
	TotalA         int64       `json:"total_a"`
	TotalB         int64       `json:"total_b"`
	Jaccard        int32       `json:"jaccard"`
}

type MvClusterStat struct {
	ClusterID      pgtype.UUID `json:"cluster_id"`
	Topic          pgtype.Text `json:"topic"`
	FirstSeenAt    interface{} `json:"first_seen_at"`
	LastSeenAt     interface{} `json:"last_seen_at"`
	ItemCount      int64       `json:"item_count"`
	UniqueChannels int64       `json:"unique_channels"`
}

type MvTopicTimeline struct {
	BucketDate    pgtype.Date `json:"bucket_date"`
	Topic         pgtype.Text `json:"topic"`
	ItemCount     int64       `json:"item_count"`
	AvgImportance float64     `json:"avg_importance"`
	AvgRelevance  float64     `json:"avg_relevance"`
}

type RawMessage struct {
	ID                   pgtype.UUID        `json:"id"`
	ChannelID            pgtype.UUID        `json:"channel_id"`
	TgMessageID          int64              `json:"tg_message_id"`
	TgDate               pgtype.Timestamptz `json:"tg_date"`
	Text                 pgtype.Text        `json:"text"`
	EntitiesJson         []byte             `json:"entities_json"`
	MediaJson            []byte             `json:"media_json"`
	CanonicalHash        string             `json:"canonical_hash"`
	IsForward            bool               `json:"is_forward"`
	InsertedAt           pgtype.Timestamptz `json:"inserted_at"`
	ProcessedAt          pgtype.Timestamptz `json:"processed_at"`
	MediaData            []byte             `json:"media_data"`
	DiscoveriesExtracted pgtype.Bool        `json:"discoveries_extracted"`
	ProcessingStartedAt  pgtype.Timestamptz `json:"processing_started_at"`
	PreviewText          pgtype.Text        `json:"preview_text"`
}

type RawMessageDropLog struct {
	ID           int32              `json:"id"`
	RawMessageID pgtype.UUID        `json:"raw_message_id"`
	Reason       string             `json:"reason"`
	Detail       pgtype.Text        `json:"detail"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type RelevanceGateLog struct {
	ID           int32              `json:"id"`
	RawMessageID pgtype.UUID        `json:"raw_message_id"`
	Decision     string             `json:"decision"`
	Confidence   pgtype.Float4      `json:"confidence"`
	Reason       pgtype.Text        `json:"reason"`
	Model        pgtype.Text        `json:"model"`
	GateVersion  pgtype.Text        `json:"gate_version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ResearchAuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     int64              `json:"user_id"`
	Route      string             `json:"route"`
	StatusCode int32              `json:"status_code"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	QueryHash  pgtype.Text        `json:"query_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ResearchSession struct {
	Token     string             `json:"token"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SchedulerLock struct {
	LockName   string             `json:"lock_name"`
	HolderID   string             `json:"holder_id"`
	AcquiredAt pgtype.Timestamptz `json:"acquired_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

type Setting struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type SettingHistory struct {
	ID        int32              `json:"id"`
	Key       string             `json:"key"`
	OldValue  pgtype.Text        `json:"old_value"`
	NewValue  pgtype.Text        `json:"new_value"`
	ChangedBy int64              `json:"changed_by"`
	ChangedAt pgtype.Timestamptz `json:"changed_at"`
}

type SummaryCache struct {
	CanonicalHash   string             `json:"canonical_hash"`
	DigestLanguage  string             `json:"digest_language"`
	Summary         string             `json:"summary"`
	Topic           pgtype.Text        `json:"topic"`
	Language        pgtype.Text        `json:"language"`
	RelevanceScore  float32            `json:"relevance_score"`
	ImportanceScore float32            `json:"importance_score"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ThresholdTuningLog struct {
	ID                  pgtype.UUID        `json:"id"`
	TunedAt             pgtype.Timestamptz `json:"tuned_at"`
	NetScore            float64            `json:"net_score"`
	Delta               float32            `json:"delta"`
	RelevanceThreshold  float32            `json:"relevance_threshold"`
	ImportanceThreshold float32            `json:"importance_threshold"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type TranslationCache struct {
	Query          string             `json:"query"`
	TargetLang     string             `json:"target_lang"`
	TranslatedText string             `json:"translated_text"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}
