// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Channel struct {
	ID                      pgtype.UUID        `json:"id"`
	TgPeerID                int64              `json:"tg_peer_id"`
	Username                pgtype.Text        `json:"username"`
	Title                   pgtype.Text        `json:"title"`
	IsActive                bool               `json:"is_active"`
	AddedAt                 pgtype.Timestamptz `json:"added_at"`
	AddedByTgUser           pgtype.Int8        `json:"added_by_tg_user"`
	AccessHash              pgtype.Int8        `json:"access_hash"`
	InviteLink              pgtype.Text        `json:"invite_link"`
	Context                 pgtype.Text        `json:"context"`
	Description             pgtype.Text        `json:"description"`
	LastTgMessageID         int64              `json:"last_tg_message_id"`
	Category                pgtype.Text        `json:"category"`
	Tone                    pgtype.Text        `json:"tone"`
	UpdateFreq              pgtype.Text        `json:"update_freq"`
	RelevanceThreshold      pgtype.Float4      `json:"relevance_threshold"`
	ImportanceThreshold     pgtype.Float4      `json:"importance_threshold"`
	ImportanceWeight        pgtype.Float4      `json:"importance_weight"`
	AutoWeightEnabled       pgtype.Bool        `json:"auto_weight_enabled"`
	WeightOverride          pgtype.Bool        `json:"weight_override"`
	WeightOverrideReason    pgtype.Text        `json:"weight_override_reason"`
	WeightUpdatedAt         pgtype.Timestamptz `json:"weight_updated_at"`
	WeightUpdatedBy         pgtype.Int8        `json:"weight_updated_by"`
	AutoRelevanceEnabled    pgtype.Bool        `json:"auto_relevance_enabled"`
	RelevanceThresholdDelta pgtype.Float4      `json:"relevance_threshold_delta"`
}

type ChannelStat struct {
	ID               int32              `json:"id"`
	ChannelID        pgtype.UUID        `json:"channel_id"`
	PeriodStart      pgtype.Date        `json:"period_start"`
	PeriodEnd        pgtype.Date        `json:"period_end"`
	MessagesReceived pgtype.Int4        `json:"messages_received"`
	ItemsCreated     pgtype.Int4        `json:"items_created"`
	ItemsDigested    pgtype.Int4        `json:"items_digested"`
	AvgImportance    pgtype.Float8      `json:"avg_importance"`
	AvgRelevance     pgtype.Float8      `json:"avg_relevance"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Cluster struct {
	ID          pgtype.UUID        `json:"id"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
	WindowEnd   pgtype.Timestamptz `json:"window_end"`
	Topic       pgtype.Text        `json:"topic"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ClusterItem struct {
	ClusterID pgtype.UUID `json:"cluster_id"`
	ItemID    pgtype.UUID `json:"item_id"`
}

type Digest struct {
	ID           pgtype.UUID        `json:"id"`
	WindowStart  pgtype.Timestamptz `json:"window_start"`
	WindowEnd    pgtype.Timestamptz `json:"window_end"`
	PostedChatID pgtype.Int8        `json:"posted_chat_id"`
	PostedMsgID  pgtype.Int8        `json:"posted_msg_id"`
	Status       string             `json:"status"`
	ErrorJson    []byte             `json:"error_json"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	PostedAt     pgtype.Timestamptz `json:"posted_at"`
}

type DigestEntry struct {
	ID          pgtype.UUID        `json:"id"`
	DigestID    pgtype.UUID        `json:"digest_id"`
	Title       pgtype.Text        `json:"title"`
	Body        string             `json:"body"`
	SourcesJson []byte             `json:"sources_json"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type DigestRating struct {
	ID        int32              `json:"id"`
	DigestID  pgtype.UUID        `json:"digest_id"`
	UserID    int64              `json:"user_id"`
	Rating    int16              `json:"rating"`
	Feedback  pgtype.Text        `json:"feedback"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DiscoveredChannel struct {
	ID                      pgtype.UUID        `json:"id"`
	Username                pgtype.Text        `json:"username"`
	TgPeerID                pgtype.Int8        `json:"tg_peer_id"`
	InviteLink              pgtype.Text        `json:"invite_link"`
	Title                   pgtype.Text        `json:"title"`
	SourceType              string             `json:"source_type"`
	DiscoveryCount          int32              `json:"discovery_count"`
	FirstSeenAt             pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt              pgtype.Timestamptz `json:"last_seen_at"`
	DiscoveredFromChannelID pgtype.UUID        `json:"discovered_from_channel_id"`
	Status                  string             `json:"status"`
	StatusChangedAt         pgtype.Timestamptz `json:"status_changed_at"`
	StatusChangedBy         pgtype.Int8        `json:"status_changed_by"`
	MaxViews                pgtype.Int4        `json:"max_views"`
	MaxForwards             pgtype.Int4        `json:"max_forwards"`
	EngagementScore         pgtype.Float4      `json:"engagement_score"`
	AccessHash              pgtype.Int8        `json:"access_hash"`
	ResolutionAttempts      pgtype.Int4        `json:"resolution_attempts"`
	LastResolutionAttempt   pgtype.Timestamptz `json:"last_resolution_attempt"`
}

type Embedding struct {
	ItemID    pgtype.UUID        `json:"item_id"`
	Embedding pgvector.Vector    `json:"embedding"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Filter struct {
	ID        pgtype.UUID        `json:"id"`
	Type      string             `json:"type"`
	Pattern   string             `json:"pattern"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Item struct {
	ID              pgtype.UUID        `json:"id"`
	RawMessageID    pgtype.UUID        `json:"raw_message_id"`
	RelevanceScore  float32            `json:"relevance_score"`
	ImportanceScore float32            `json:"importance_score"`
	Topic           pgtype.Text        `json:"topic"`
	Summary         pgtype.Text        `json:"summary"`
	Language        pgtype.Text        `json:"language"`
	Status          string             `json:"status"`
	ErrorJson       []byte             `json:"error_json"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	DigestedAt      pgtype.Timestamptz `json:"digested_at"`
	RetryCount      int32              `json:"retry_count"`
	NextRetryAt     pgtype.Timestamptz `json:"next_retry_at"`
}

type ItemRating struct {
	ID        int32              `json:"id"`
	ItemID    pgtype.UUID        `json:"item_id"`
	UserID    int64              `json:"user_id"`
	Rating    string             `json:"rating"`
	Feedback  pgtype.Text        `json:"feedback"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type LinkCache struct {
	ID              pgtype.UUID        `json:"id"`
	Url             string             `json:"url"`
	Domain          string             `json:"domain"`
	LinkType        string             `json:"link_type"`
	Title           pgtype.Text        `json:"title"`
	Content         pgtype.Text        `json:"content"`
	Author          pgtype.Text        `json:"author"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	Description     pgtype.Text        `json:"description"`
	ImageUrl        pgtype.Text        `json:"image_url"`
	WordCount       pgtype.Int4        `json:"word_count"`
	ChannelUsername pgtype.Text        `json:"channel_username"`
	ChannelTitle    pgtype.Text        `json:"channel_title"`
	ChannelID       pgtype.Int8        `json:"channel_id"`
	MessageID       pgtype.Int8        `json:"message_id"`
	Views           pgtype.Int4        `json:"views"`
	Forwards        pgtype.Int4        `json:"forwards"`
	HasMedia        pgtype.Bool        `json:"has_media"`
	MediaType       pgtype.Text        `json:"media_type"`
	Status          string             `json:"status"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	Language        pgtype.Text        `json:"language"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

type MessageLink struct {
	RawMessageID pgtype.UUID `json:"raw_message_id"`
	LinkCacheID  pgtype.UUID `json:"link_cache_id"`
	Position     pgtype.Int4 `json:"position"`
}

type RawMessage struct {
	ID                   pgtype.UUID        `json:"id"`
	ChannelID            pgtype.UUID        `json:"channel_id"`
	TgMessageID          int64              `json:"tg_message_id"`
	TgDate               pgtype.Timestamptz `json:"tg_date"`
	Text                 pgtype.Text        `json:"text"`
	EntitiesJson         []byte             `json:"entities_json"`
	MediaJson            []byte             `json:"media_json"`
	CanonicalHash        string             `json:"canonical_hash"`
	IsForward            bool               `json:"is_forward"`
	InsertedAt           pgtype.Timestamptz `json:"inserted_at"`
	ProcessedAt          pgtype.Timestamptz `json:"processed_at"`
	MediaData            []byte             `json:"media_data"`
	DiscoveriesExtracted pgtype.Bool        `json:"discoveries_extracted"`
}

type RelevanceGateLog struct {
	ID           int32              `json:"id"`
	RawMessageID pgtype.UUID        `json:"raw_message_id"`
	Decision     string             `json:"decision"`
	Confidence   pgtype.Float4      `json:"confidence"`
	Reason       pgtype.Text        `json:"reason"`
	Model        pgtype.Text        `json:"model"`
	GateVersion  pgtype.Text        `json:"gate_version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Setting struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type SettingHistory struct {
	ID        int32              `json:"id"`
	Key       string             `json:"key"`
	OldValue  pgtype.Text        `json:"old_value"`
	NewValue  pgtype.Text        `json:"new_value"`
	ChangedBy int64              `json:"changed_by"`
	ChangedAt pgtype.Timestamptz `json:"changed_at"`
}
