// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddChannel(ctx context.Context, arg AddChannelParams) error
	AddChannelByID(ctx context.Context, tgPeerID int64) error
	AddChannelByInviteLink(ctx context.Context, inviteLink pgtype.Text) error
	AddChannelByUsername(ctx context.Context, username pgtype.Text) error
	AddFilter(ctx context.Context, arg AddFilterParams) error
	AddSettingHistory(ctx context.Context, arg AddSettingHistoryParams) error
	AddToCluster(ctx context.Context, arg AddToClusterParams) error
	CheckAndMarkDiscoveriesExtracted(ctx context.Context, arg CheckAndMarkDiscoveriesExtractedParams) (pgtype.UUID, error)
	CheckStrictDuplicate(ctx context.Context, arg CheckStrictDuplicateParams) (bool, error)
	ClearDigestErrors(ctx context.Context) error
	CountActiveChannels(ctx context.Context) (int64, error)
	CountItemsInWindow(ctx context.Context, arg CountItemsInWindowParams) (int64, error)
	CountReadyItems(ctx context.Context) (int64, error)
	CountReadyItemsInWindow(ctx context.Context, arg CountReadyItemsInWindowParams) (int64, error)
	CountRecentlyActiveChannels(ctx context.Context) (int64, error)
	CreateCluster(ctx context.Context, arg CreateClusterParams) (pgtype.UUID, error)
	DeactivateChannel(ctx context.Context, username pgtype.Text) error
	DeactivateFilter(ctx context.Context, pattern string) error
	DeleteClustersForWindow(ctx context.Context, arg DeleteClustersForWindowParams) error
	DeleteSetting(ctx context.Context, key string) error
	DigestExists(ctx context.Context, arg DigestExistsParams) (bool, error)
	FindSimilarItem(ctx context.Context, arg FindSimilarItemParams) (pgtype.UUID, error)
	GetActiveChannels(ctx context.Context) ([]GetActiveChannelsRow, error)
	GetActiveFilters(ctx context.Context) ([]GetActiveFiltersRow, error)
	GetAllSettings(ctx context.Context) ([]GetAllSettingsRow, error)
	GetBacklogCount(ctx context.Context) (int64, error)
	GetChannelByID(ctx context.Context, id pgtype.UUID) (GetChannelByIDRow, error)
	GetChannelByPeerID(ctx context.Context, tgPeerID int64) (Channel, error)
	GetChannelStats(ctx context.Context) ([]GetChannelStatsRow, error)
	GetChannelStatsForPeriod(ctx context.Context, arg GetChannelStatsForPeriodParams) ([]GetChannelStatsForPeriodRow, error)
	GetChannelStatsForWindow(ctx context.Context, arg GetChannelStatsForWindowParams) ([]GetChannelStatsForWindowRow, error)
	GetChannelStatsRolling(ctx context.Context, arg GetChannelStatsRollingParams) (GetChannelStatsRollingRow, error)
	GetChannelWeight(ctx context.Context, username pgtype.Text) (GetChannelWeightRow, error)
	GetChannelsForAutoWeight(ctx context.Context) ([]GetChannelsForAutoWeightRow, error)
	GetClustersForWindow(ctx context.Context, arg GetClustersForWindowParams) ([]GetClustersForWindowRow, error)
	GetDigestCoverImage(ctx context.Context, arg GetDigestCoverImageParams) ([]byte, error)
	GetDiscoveriesNeedingResolution(ctx context.Context, limit int32) ([]GetDiscoveriesNeedingResolutionRow, error)
	GetDiscoveryByUsername(ctx context.Context, username pgtype.Text) (GetDiscoveryByUsernameRow, error)
	GetDiscoveryFilterStats(ctx context.Context, arg GetDiscoveryFilterStatsParams) (GetDiscoveryFilterStatsRow, error)
	GetDiscoveryStats(ctx context.Context) (GetDiscoveryStatsRow, error)
	GetInviteLinkDiscoveriesNeedingResolution(ctx context.Context, limit int32) ([]GetInviteLinkDiscoveriesNeedingResolutionRow, error)
	GetItemByID(ctx context.Context, id pgtype.UUID) (GetItemByIDRow, error)
	GetItemEmbedding(ctx context.Context, itemID pgtype.UUID) (string, error)
	GetItemRatingsSince(ctx context.Context, createdAt pgtype.Timestamptz) ([]GetItemRatingsSinceRow, error)
	GetItemsForWindow(ctx context.Context, arg GetItemsForWindowParams) ([]GetItemsForWindowRow, error)
	GetItemsForWindowWithMedia(ctx context.Context, arg GetItemsForWindowWithMediaParams) ([]GetItemsForWindowWithMediaRow, error)
	GetLastPostedDigest(ctx context.Context) (GetLastPostedDigestRow, error)
	GetLinkCache(ctx context.Context, url string) (LinkCache, error)
	GetLinksForMessage(ctx context.Context, rawMessageID pgtype.UUID) ([]LinkCache, error)
	// Only return actionable discoveries (with username for approve/reject)
	// Uses DISTINCT ON to deduplicate multiple rows for the same channel (discovered via different identifiers)
	GetPendingDiscoveries(ctx context.Context, arg GetPendingDiscoveriesParams) ([]GetPendingDiscoveriesRow, error)
	GetRecentErrors(ctx context.Context, limit int32) ([]GetRecentErrorsRow, error)
	GetRecentMessagesForChannel(ctx context.Context, arg GetRecentMessagesForChannelParams) ([]GetRecentMessagesForChannelRow, error)
	GetRecentSettingHistory(ctx context.Context, limit int32) ([]GetRecentSettingHistoryRow, error)
	GetRejectedDiscoveries(ctx context.Context, limit int32) ([]GetRejectedDiscoveriesRow, error)
	GetSetting(ctx context.Context, key string) ([]byte, error)
	GetUnprocessedMessages(ctx context.Context, limit int32) ([]GetUnprocessedMessagesRow, error)
	IncrementDiscoveryResolutionAttempts(ctx context.Context, id pgtype.UUID) error
	IsChannelDiscoveredRejected(ctx context.Context, arg IsChannelDiscoveredRejectedParams) (bool, error)
	IsChannelTracked(ctx context.Context, arg IsChannelTrackedParams) (bool, error)
	LinkMessageToLink(ctx context.Context, arg LinkMessageToLinkParams) error
	MarkAsProcessed(ctx context.Context, id pgtype.UUID) error
	MarkItemsAsDigested(ctx context.Context, dollar_1 []pgtype.UUID) error
	ReleaseAdvisoryLock(ctx context.Context, pgAdvisoryUnlock int64) error
	RetryFailedItems(ctx context.Context) error
	RetryItem(ctx context.Context, id pgtype.UUID) error
	SaveDigest(ctx context.Context, arg SaveDigestParams) (pgtype.UUID, error)
	SaveDigestEntry(ctx context.Context, arg SaveDigestEntryParams) error
	SaveDigestError(ctx context.Context, arg SaveDigestErrorParams) error
	SaveEmbedding(ctx context.Context, arg SaveEmbeddingParams) error
	SaveItem(ctx context.Context, arg SaveItemParams) (pgtype.UUID, error)
	SaveItemError(ctx context.Context, arg SaveItemErrorParams) error
	SaveItemRating(ctx context.Context, arg SaveItemRatingParams) error
	SaveLinkCache(ctx context.Context, arg SaveLinkCacheParams) (pgtype.UUID, error)
	SaveRating(ctx context.Context, arg SaveRatingParams) error
	SaveRawMessage(ctx context.Context, arg SaveRawMessageParams) error
	SaveSetting(ctx context.Context, arg SaveSettingParams) error
	TryAcquireAdvisoryLock(ctx context.Context, pgTryAdvisoryLock int64) (bool, error)
	UpdateChannel(ctx context.Context, arg UpdateChannelParams) error
	UpdateChannelAutoWeight(ctx context.Context, arg UpdateChannelAutoWeightParams) error
	UpdateChannelContext(ctx context.Context, arg UpdateChannelContextParams) error
	UpdateChannelLastMessageID(ctx context.Context, arg UpdateChannelLastMessageIDParams) error
	UpdateChannelMetadata(ctx context.Context, arg UpdateChannelMetadataParams) error
	UpdateChannelRelevanceDelta(ctx context.Context, arg UpdateChannelRelevanceDeltaParams) error
	// Channel importance weight queries
	UpdateChannelWeight(ctx context.Context, arg UpdateChannelWeightParams) (UpdateChannelWeightRow, error)
	UpdateDiscoveryChannelInfo(ctx context.Context, arg UpdateDiscoveryChannelInfoParams) error
	UpdateDiscoveryFromInvite(ctx context.Context, arg UpdateDiscoveryFromInviteParams) error
	UpdateDiscoveryStatus(ctx context.Context, arg UpdateDiscoveryStatusParams) error
	// Rejects the target row AND any related rows that share peer_id or invite_link
	// This prevents the same channel from reappearing via different discovery paths
	UpdateDiscoveryStatusByUsername(ctx context.Context, arg UpdateDiscoveryStatusByUsernameParams) error
	// Channel stats queries
	UpsertChannelStats(ctx context.Context, arg UpsertChannelStatsParams) error
	UpsertDiscoveredChannelByInvite(ctx context.Context, arg UpsertDiscoveredChannelByInviteParams) error
	UpsertDiscoveredChannelByPeerID(ctx context.Context, arg UpsertDiscoveredChannelByPeerIDParams) error
	// Channel Discovery queries
	UpsertDiscoveredChannelByUsername(ctx context.Context, arg UpsertDiscoveredChannelByUsernameParams) error
}

var _ Querier = (*Queries)(nil)
