// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddChannel(ctx context.Context, arg AddChannelParams) error
	AddChannelByID(ctx context.Context, tgPeerID int64) error
	AddChannelByInviteLink(ctx context.Context, inviteLink pgtype.Text) error
	AddChannelByUsername(ctx context.Context, username pgtype.Text) error
	AddFilter(ctx context.Context, arg AddFilterParams) error
	AddItemLinkLangQueries(ctx context.Context, arg AddItemLinkLangQueriesParams) error
	AddSettingHistory(ctx context.Context, arg AddSettingHistoryParams) error
	AddToCluster(ctx context.Context, arg AddToClusterParams) error
	CheckAndMarkDiscoveriesExtracted(ctx context.Context, arg CheckAndMarkDiscoveriesExtractedParams) (pgtype.UUID, error)
	CheckStrictDuplicate(ctx context.Context, arg CheckStrictDuplicateParams) (bool, error)
	ClearDigestErrors(ctx context.Context) error
	CountActiveChannels(ctx context.Context) (int64, error)
	CountItemsInWindow(ctx context.Context, arg CountItemsInWindowParams) (int64, error)
	CountReadyItems(ctx context.Context) (int64, error)
	CountReadyItemsInWindow(ctx context.Context, arg CountReadyItemsInWindowParams) (int64, error)
	CountRecentlyActiveChannels(ctx context.Context) (int64, error)
	CreateCluster(ctx context.Context, arg CreateClusterParams) (pgtype.UUID, error)
	DeactivateChannel(ctx context.Context, username pgtype.Text) error
	DeactivateChannelByID(ctx context.Context, id pgtype.UUID) error
	DeactivateFilter(ctx context.Context, pattern string) error
	DeleteClustersForWindow(ctx context.Context, arg DeleteClustersForWindowParams) error
	DeleteSetting(ctx context.Context, key string) error
	DigestExists(ctx context.Context, arg DigestExistsParams) (bool, error)
	// Extends the lock expiry time (heartbeat)
	ExtendSchedulerLock(ctx context.Context, arg ExtendSchedulerLockParams) error
	FindSimilarItem(ctx context.Context, arg FindSimilarItemParams) (pgtype.UUID, error)
	GetActiveChannels(ctx context.Context) ([]GetActiveChannelsRow, error)
	GetActiveFilters(ctx context.Context) ([]GetActiveFiltersRow, error)
	GetAllSettings(ctx context.Context) ([]GetAllSettingsRow, error)
	GetBacklogCount(ctx context.Context) (int64, error)
	// Handles both canonical bullets and duplicate bullets whose canonical may be outside the digest.
	// For duplicates, joins to canonical bullet to get text while keeping digest item's source info.
	GetBulletsForDigest(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetBulletsForDigestRow, error)
	GetBulletsForItem(ctx context.Context, itemID pgtype.UUID) ([]ItemBullet, error)
	GetBulletsForItems(ctx context.Context, dollar_1 []pgtype.UUID) ([]ItemBullet, error)
	GetChannelByID(ctx context.Context, id pgtype.UUID) (GetChannelByIDRow, error)
	GetChannelByPeerID(ctx context.Context, tgPeerID int64) (Channel, error)
	GetChannelStats(ctx context.Context) ([]GetChannelStatsRow, error)
	GetChannelStatsForPeriod(ctx context.Context, arg GetChannelStatsForPeriodParams) ([]GetChannelStatsForPeriodRow, error)
	GetChannelStatsForWindow(ctx context.Context, arg GetChannelStatsForWindowParams) ([]GetChannelStatsForWindowRow, error)
	GetChannelStatsRolling(ctx context.Context, arg GetChannelStatsRollingParams) (GetChannelStatsRollingRow, error)
	GetChannelWeight(ctx context.Context, username pgtype.Text) (GetChannelWeightRow, error)
	GetChannelsForAutoWeight(ctx context.Context) ([]GetChannelsForAutoWeightRow, error)
	// Cluster Summary Cache queries
	GetClusterSummaryCache(ctx context.Context, arg GetClusterSummaryCacheParams) ([]GetClusterSummaryCacheRow, error)
	GetClusterSummaryCacheEntry(ctx context.Context, arg GetClusterSummaryCacheEntryParams) (GetClusterSummaryCacheEntryRow, error)
	GetClustersForWindow(ctx context.Context, arg GetClustersForWindowParams) ([]GetClustersForWindowRow, error)
	GetDigestCoverImage(ctx context.Context, arg GetDigestCoverImageParams) ([]byte, error)
	GetDiscoveriesNeedingResolution(ctx context.Context, limit int32) ([]GetDiscoveriesNeedingResolutionRow, error)
	GetDiscoveryByUsername(ctx context.Context, lower string) (GetDiscoveryByUsernameRow, error)
	GetDiscoveryFilterStats(ctx context.Context, arg GetDiscoveryFilterStatsParams) (GetDiscoveryFilterStatsRow, error)
	GetDiscoveryStats(ctx context.Context) (GetDiscoveryStatsRow, error)
	GetDropReasonStats(ctx context.Context, arg GetDropReasonStatsParams) ([]GetDropReasonStatsRow, error)
	GetEnrichmentErrors(ctx context.Context, limit int32) ([]GetEnrichmentErrorsRow, error)
	GetEnrichmentQueueStats(ctx context.Context) ([]GetEnrichmentQueueStatsRow, error)
	GetInviteLinkDiscoveriesNeedingResolution(ctx context.Context, limit int32) ([]GetInviteLinkDiscoveriesNeedingResolutionRow, error)
	GetItemByCanonicalURL(ctx context.Context, arg GetItemByCanonicalURLParams) (GetItemByCanonicalURLRow, error)
	GetItemByID(ctx context.Context, id pgtype.UUID) (GetItemByIDRow, error)
	GetItemEmbedding(ctx context.Context, itemID pgtype.UUID) (string, error)
	GetItemRatingsByItem(ctx context.Context, arg GetItemRatingsByItemParams) ([]GetItemRatingsByItemRow, error)
	GetItemRatingsSince(ctx context.Context, createdAt pgtype.Timestamptz) ([]GetItemRatingsSinceRow, error)
	GetItemsForWindow(ctx context.Context, arg GetItemsForWindowParams) ([]GetItemsForWindowRow, error)
	GetItemsForWindowWithMedia(ctx context.Context, arg GetItemsForWindowWithMediaParams) ([]GetItemsForWindowWithMediaRow, error)
	GetLastPostedDigest(ctx context.Context) (GetLastPostedDigestRow, error)
	GetLatestChannelRatingStats(ctx context.Context, limit int32) ([]GetLatestChannelRatingStatsRow, error)
	GetLatestGlobalRatingStats(ctx context.Context) (GetLatestGlobalRatingStatsRow, error)
	GetLinkCache(ctx context.Context, url string) (LinkCache, error)
	GetLinksForMessage(ctx context.Context, rawMessageID pgtype.UUID) ([]LinkCache, error)
	// Returns pending bullets plus recent ready bullets for global deduplication.
	// Ready bullets within the lookback window serve as canonical candidates.
	// Pending bullets are ordered last so they get deduplicated against ready bullets.
	GetPendingBulletsForDedup(ctx context.Context, dollar_1 pgtype.Interval) ([]GetPendingBulletsForDedupRow, error)
	// Only return actionable discoveries (with username for approve/reject)
	// Uses DISTINCT ON to deduplicate multiple rows for the same channel (discovered via different identifiers)
	GetPendingDiscoveries(ctx context.Context, arg GetPendingDiscoveriesParams) ([]GetPendingDiscoveriesRow, error)
	// Same as GetPendingDiscoveries but without a limit, used for keyword filtering stats.
	GetPendingDiscoveriesForFiltering(ctx context.Context, arg GetPendingDiscoveriesForFilteringParams) ([]GetPendingDiscoveriesForFilteringRow, error)
	GetRecentErrors(ctx context.Context, limit int32) ([]GetRecentErrorsRow, error)
	GetRecentMessagesForChannel(ctx context.Context, arg GetRecentMessagesForChannelParams) ([]GetRecentMessagesForChannelRow, error)
	GetRecentSettingHistory(ctx context.Context, limit int32) ([]GetRecentSettingHistoryRow, error)
	GetRejectedDiscoveries(ctx context.Context, limit int32) ([]GetRejectedDiscoveriesRow, error)
	GetSetting(ctx context.Context, key string) ([]byte, error)
	// Summary Cache queries
	GetSummaryCache(ctx context.Context, arg GetSummaryCacheParams) (GetSummaryCacheRow, error)
	// Uses FOR UPDATE SKIP LOCKED to prevent multiple workers from claiming the same messages.
	// Atomically claims messages by setting processing_started_at.
	GetUnprocessedMessages(ctx context.Context, limit int32) ([]GetUnprocessedMessagesRow, error)
	IncrementDiscoveryResolutionAttempts(ctx context.Context, id pgtype.UUID) error
	// ============================================================================
	// Bullet extraction queries
	// ============================================================================
	InsertBullet(ctx context.Context, arg InsertBulletParams) (pgtype.UUID, error)
	InsertThresholdTuningLog(ctx context.Context, arg InsertThresholdTuningLogParams) error
	IsChannelDiscoveredRejected(ctx context.Context, arg IsChannelDiscoveredRejectedParams) (bool, error)
	IsChannelTracked(ctx context.Context, arg IsChannelTrackedParams) (bool, error)
	LinkMessageToLink(ctx context.Context, arg LinkMessageToLinkParams) error
	MarkAsProcessed(ctx context.Context, id pgtype.UUID) error
	MarkBulletAsCanonical(ctx context.Context, id pgtype.UUID) error
	MarkBulletAsDuplicateOf(ctx context.Context, arg MarkBulletAsDuplicateOfParams) error
	MarkDuplicateBullets(ctx context.Context, dollar_1 []pgtype.UUID) error
	MarkItemsAsDigested(ctx context.Context, dollar_1 []pgtype.UUID) error
	// Recovers messages that were claimed but not processed within the timeout.
	// This handles cases where a worker crashed after claiming messages.
	RecoverStuckPipelineMessages(ctx context.Context, dollar_1 pgtype.Interval) (int64, error)
	ReleaseAdvisoryLock(ctx context.Context, pgAdvisoryUnlock int64) error
	// Releases a claimed message so it can be picked up by another worker (used on error)
	ReleaseClaimedMessage(ctx context.Context, id pgtype.UUID) error
	// Releases the lock if held by the specified holder
	ReleaseSchedulerLock(ctx context.Context, arg ReleaseSchedulerLockParams) error
	RetryFailedEnrichmentItems(ctx context.Context) error
	RetryFailedItems(ctx context.Context) error
	RetryItem(ctx context.Context, id pgtype.UUID) error
	SaveDigest(ctx context.Context, arg SaveDigestParams) (pgtype.UUID, error)
	SaveDigestEntry(ctx context.Context, arg SaveDigestEntryParams) error
	SaveDigestError(ctx context.Context, arg SaveDigestErrorParams) error
	SaveEmbedding(ctx context.Context, arg SaveEmbeddingParams) error
	SaveItem(ctx context.Context, arg SaveItemParams) (pgtype.UUID, error)
	SaveItemError(ctx context.Context, arg SaveItemErrorParams) error
	SaveItemRating(ctx context.Context, arg SaveItemRatingParams) error
	SaveLinkCache(ctx context.Context, arg SaveLinkCacheParams) (pgtype.UUID, error)
	SaveRating(ctx context.Context, arg SaveRatingParams) error
	SaveRawMessage(ctx context.Context, arg SaveRawMessageParams) error
	// Drop Log queries
	SaveRawMessageDropLog(ctx context.Context, arg SaveRawMessageDropLogParams) error
	// Relevance Gate Log queries
	SaveRelevanceGateLog(ctx context.Context, arg SaveRelevanceGateLogParams) error
	SaveSetting(ctx context.Context, arg SaveSettingParams) error
	TryAcquireAdvisoryLock(ctx context.Context, pgTryAdvisoryLock int64) (bool, error)
	// Tries to acquire a row-based lock. Returns true if acquired.
	// Automatically expires stale locks older than the specified duration.
	TryAcquireSchedulerLock(ctx context.Context, arg TryAcquireSchedulerLockParams) (bool, error)
	UpdateBulletEmbedding(ctx context.Context, arg UpdateBulletEmbeddingParams) error
	UpdateBulletStatus(ctx context.Context, arg UpdateBulletStatusParams) error
	UpdateChannel(ctx context.Context, arg UpdateChannelParams) error
	UpdateChannelAutoWeight(ctx context.Context, arg UpdateChannelAutoWeightParams) error
	UpdateChannelContext(ctx context.Context, arg UpdateChannelContextParams) error
	UpdateChannelLastMessageID(ctx context.Context, arg UpdateChannelLastMessageIDParams) error
	UpdateChannelMetadata(ctx context.Context, arg UpdateChannelMetadataParams) error
	UpdateChannelRelevanceDelta(ctx context.Context, arg UpdateChannelRelevanceDeltaParams) error
	// Channel importance weight queries
	UpdateChannelWeight(ctx context.Context, arg UpdateChannelWeightParams) (UpdateChannelWeightRow, error)
	UpdateDiscoveryChannelInfo(ctx context.Context, arg UpdateDiscoveryChannelInfoParams) error
	UpdateDiscoveryFromInvite(ctx context.Context, arg UpdateDiscoveryFromInviteParams) error
	UpdateDiscoveryStatus(ctx context.Context, arg UpdateDiscoveryStatusParams) error
	// Rejects the target row AND any related rows that share peer_id or invite_link
	// This prevents the same channel from reappearing via different discovery paths
	UpdateDiscoveryStatusByUsername(ctx context.Context, arg UpdateDiscoveryStatusByUsernameParams) error
	UpsertChannelQualityHistory(ctx context.Context, arg UpsertChannelQualityHistoryParams) error
	// Channel Rating Stats queries
	UpsertChannelRatingStats(ctx context.Context, arg UpsertChannelRatingStatsParams) error
	// Channel stats queries
	UpsertChannelStats(ctx context.Context, arg UpsertChannelStatsParams) error
	UpsertClusterSummaryCache(ctx context.Context, arg UpsertClusterSummaryCacheParams) error
	UpsertDiscoveredChannelByInvite(ctx context.Context, arg UpsertDiscoveredChannelByInviteParams) error
	UpsertDiscoveredChannelByPeerID(ctx context.Context, arg UpsertDiscoveredChannelByPeerIDParams) error
	// Channel Discovery queries
	UpsertDiscoveredChannelByUsername(ctx context.Context, arg UpsertDiscoveredChannelByUsernameParams) error
	UpsertGlobalRatingStats(ctx context.Context, arg UpsertGlobalRatingStatsParams) error
	UpsertItemCanonicalLink(ctx context.Context, arg UpsertItemCanonicalLinkParams) error
	UpsertItemLinkDebug(ctx context.Context, arg UpsertItemLinkDebugParams) error
	UpsertSummaryCache(ctx context.Context, arg UpsertSummaryCacheParams) error
}

var _ Querier = (*Queries)(nil)
